#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	apt-get="sudo apt-get" \
        reboot="sudo reboot"

# Custom aliases
alias edzsh="vim ~/.zshrc"
alias srczsh="source ~/.config/zsh/.zshrc"
alias myip="ip address | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | grep -v '172'"
alias dfv="df -h -x squashfs -x tmpfs -x devtmpfs"
alias nf="neofetch"
alias c='tty-clock -c -C 7 -S'
alias bto="bluetoothctl power on"
alias hg="history | grep"
alias sus="systemctl suspend"
alias d="cd ~/Documents"
alias D="cd ~/Downloads"
alias nit="nitrogen ~/Pictures/Backgrounds"
alias bat="batcat"
